### ISSUE TITLE
stream operators for chunks

### ISSUE THREAD

**Issue by Raildex** [libdmusic/riffcpp#1]
Would it be possible to add stream operators (`<<` and `>>`) for chunks?
Something along those lines:

```
riffcpp::Chunk ch(...);
// current chunk stream position is data[0];
short value;
value << ch;
//chunk stream position is now at data[0 + sizeof(short)];
```

This would allow clients to get rid of the `Chunk::read_data(char*,size_t)` function which reads untyped data.

**Comment by frabert** [comment]
I have an issue with this approach, because it seems a little ambiguous to me.
For example, with regular streams, doing `short value; stream >> value;` implies parsing being done. That is, a string representation is consumed and converted to numerical values.

Moreover, it is not portable. What byte order does the data have when reading? Machine-native, always LE, always BE? You can't specify it with this syntax. The correct way to read binary data is to copy to a buffer, then use `ntohs` or equivalent functions to correct the ordering.
